# Generated by Django 3.2.7 on 2021-09-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210916_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addon',
            field=models.ManyToManyField(to='catalog.Addon'),
        ),
    ]
